//auto-generated: awk -f csv2map.awk glyph-sequences.csv | sed -e '/\/\/auto-generated:/r /dev/stdin' -e '/\/\/auto-generated:/,/\/\/end-auto-generated/{//!d;}' -i modules/sequences.mjs
const glyphSequencesMap = new Map([
	[
		"abandon",
		[
			["all","technology","save","us"],
			["fear","defend","future"],
			["fear","defend","future","together"],
			["fear","see","future"],
			["fear","see","future","destination"],
			["fear","together"],
			["war","create","love"],
		],
	],
	[
		"accept",
		[
			["human","inside","n","l"],
			["human","weak"],
			["weak","love","self"],
		],
	],
	[
		"adapt",
		[
			["create","new","future","together"],
			["idea","discover","evolution"],
			["technology"],
			["thought","discover","evolution"],
			["thought","discover","simple","success"],
		],
	],
	[
		"advance",
		[
			["civilization","pursue","shapers","path"],
			["civilization","pursue","shapers","truth"],
			["civilization","repeat","failure"],
			["enlightenment"],
			["human","enlightenment"],
			["human","resistance"],
			["pure","truth"],
			["resistance"],
			["truth"],
		],
	],
	[
		"after",
		[
			["imperfect","human","presence","consequence"],
		],
	],
	[
		"again",
		[
			["journey","outside"],
		],
	],
	[
		"all",
		[
			["answer","inside","love"],
			["chaos"],
			["chaos","inside","body"],
			["civilization","chaos"],
			["safety","inside","love"],
			["xm","liberate"],
		],
	],
	[
		"answer",
		[
			["nzeer","question"],
			["nzeer","question","potential","knowledge"],
			["question","discover","difficult","truth"],
			["repeat","struggle"],
		],
	],
	[
		"attack",
		[
			["capture","link"],
			["difficult","future"],
			["enlightenment","pursue","resistance"],
			["resistance","pursue","enlightenment"],
			["shapers","chaos"],
			["shapers","evolution"],
			["shapers","portal"],
			["weak","shapers","lie"],
		],
	],
	[
		"avoid",
		[
			["attack","chaos"],
			["balance","stability","human","self"],
			["chaos"],
			["chaos","avoid","shapers","lie"],
			["chaos","have","self","love"],
			["chaos","repair","potential","war"],
			["chaos","soul"],
			["complex","conflict"],
			["complex","soul"],
			["complex","truth"],
			["conflict"],
			["destiny","lie"],
			["impure","evolution"],
			["perfection","stay","human","self"],
			["pure","chaos"],
			["war","chaos"],
			["xm","message","lie"],
		],
	],
	[
		"before",
		[
			["mystery","after","knowledge"],
		],
	],
	[
		"begin",
		[
			["human","legacy","now"],
			["journey","breathe","xm"],
			["journey","breathe","xm","evolution"],
			["new","journey"],
			["new","n","l","journey"],
			["new","struggle"],
		],
	],
	[
		"breathe",
		[
			["again","journey","again"],
			["inside","xm","lose","self"],
			["love"],
			["nature","perfection","harmony"],
		],
	],
	[
		"capture",
		[
			["fear","discover","courage"],
			["heart","capture","human"],
			["portal","defend","portal","courage"],
			["shapers","portal"],
			["victory","together"],
			["xm"],
			["xm","portal"],
		],
	],
	[
		"change",
		[
			["body","improve","human"],
			["future"],
			["future","capture","destiny"],
			["human","destiny","discover","love"],
			["human","destiny","use","love"],
			["human","future"],
			["human","potential","use"],
			["now"],
			["perspective"],
			["perspective","begin","new"],
			["perspective","begin","new","struggle"],
			["perspective","save","heart","soul"],
			["perspective","technology"],
		],
	],
	[
		"chaos",
		[
			["attack","conflict","discover","harmony"],
			["barrier","shapers","portal"],
			["perfection","stability","human","self"],
		],
	],
	[
		"civilization",
		[
			["war","chaos"],
		],
	],
	[
		"clear",
		[
			["consequence"],
			["mind","liberate","barrier","body"],
			["mind","open","mind"],
			["path","help","n","l"],
			["your","mind"],
			["your","mind","creativity","grow"],
			["your","mind","more","balance"],
		],
	],
	[
		"clearall",
		[
			["idea","past","present","future"],
			["link"],
			["openall","discover","truth"],
		],
	],
	[
		"complex",
		[
			["future"],
			["journey","future"],
			["shapers","civilization","strong"],
		],
	],
	[
		"conflict",
		[
			["grow","war"],
			["grow","war","danger"],
			["heart","conflict","soul"],
		],
	],
	[
		"contemplate",
		[
			["chaos","before","link"],
			["complex","shapers","civilization"],
			["complex","shapers","truth"],
			["field","pursue","human","legacy"],
			["future","not","shapers","path"],
			["journey"],
			["journey","outside"],
			["love"],
			["potential","journey"],
			["potential","perfection"],
			["restraint","discover","more","courage"],
			["self","path","truth"],
		],
	],
	[
		"courage",
		[
			["attack","shapers","future"],
			["attack","shapers","portal","together"],
			["destiny","rebel"],
			["love","self"],
			["war","shapers","future"],
		],
	],
	[
		"create",
		[
			["danger"],
			["distance","impure","path"],
			["future","change","destiny"],
			["future","journey"],
			["future","not","war"],
			["love","not","war"],
			["love","together"],
			["new","future"],
			["new","future","see","all"],
			["new","portal","potential"],
			["new","portal","potential","future"],
			["pure","future","human","civilization"],
			["pure","future","not","war"],
			["separate","path","end","journey"],
			["truth","legacy"],
		],
	],
	[
		"danger",
		[
			["change","past"],
		],
	],
	[
		"death",
		[
			["end","love","not"],
		],
	],
	[
		"defend",
		[
			["destiny","defend","human","civilization"],
			["field","gain","victory"],
			["heart"],
			["human","civilization","portal","data"],
			["human","civilization","shapers","lie"],
			["human","civilization","shapers","portal"],
			["human","civilization","xm","message"],
			["human","lie"],
			["human","nzeer","lie"],
			["message","answer","idea"],
			["pure","love"],
			["search","safety"],
		],
	],
	[
		"destroy",
		[
			["civilization","danger"],
			["civilization","end","conflict","war"],
			["complex","shapers","lie"],
			["destiny","barrier"],
			["destiny","human","lie"],
			["difficult","barrier"],
			["field","capture","key"],
			["impure","truth"],
			["lie","inside","gain","soul"],
			["liveagain"],
			["portal","shield"],
			["weak","civilization"],
		],
	],
	[
		"deteriorate",
		[
			["advance","present"],
			["human","weak","rebel"],
		],
	],
	[
		"difficult",
		[
			["journey","pursue","n","l"],
			["journey","strong","body"],
			["knowledge","advance","mind"],
		],
	],
	[
		"discover",
		[
			["destiny","inside","love"],
			["enlightenment"],
			["harmony","equal"],
			["key"],
			["love"],
			["love","discover","harmony"],
			["love","inside","journey"],
			["n","l","technology","outside"],
			["path"],
			["portal"],
			["portal","truth"],
			["pure","truth"],
			["resistance","truth"],
			["safety","civilization"],
			["shapers","civilization"],
			["shapers","enlightenment"],
			["shapers","lie"],
			["shapers","message"],
			["truth"],
		],
	],
	[
		"distance",
		[
			["impure","love","lie"],
			["self","avoid","human","lie"],
		],
	],
	[
		"easy",
		[
			["path","future","follow","shapers"],
		],
	],
	[
		"end",
		[
			["journey","discover","destiny"],
			["old","civilization","create","new"],
		],
	],
	[
		"enlightened",
		[
			["capture","victory","together"],
		],
	],
	[
		"enlightenment",
		[
			["resistance","love","strong","civilization"],
		],
	],
	[
		"escape",
		[
			["before","death","end","all"],
			["before","pure","death"],
			["body","journey","outside","now"],
			["body","mind","self","want"],
			["evolution"],
			["harm"],
			["impure","evolution"],
			["impure","future"],
			["impure","truth"],
			["portal","harm"],
			["shapers","harm"],
			["shapers","harmony"],
			["simple","human","future"],
			["together"],
		],
	],
	[
		"fear",
		[
			["chaos","xm"],
			["complex","xm"],
			["imperfect","nzeer","technology"],
			["imperfect","technology"],
		],
	],
	[
		"field",
		[
			["all"],
			["all","mind"],
			["before","civilization"],
			["nourish","civilization"],
			["together","improve","human","mind"],
		],
	],
	[
		"follow",
		[
			["1","3","3","1"],
			["journey"],
			["path","see","nature"],
			["pure","journey"],
			["shapers","portal","message"],
			["your","heart"],
		],
	],
	[
		"forget",
		[
			["conflict","accept","war"],
			["harm","forget","lie","love"],
			["love","not"],
			["past","conflict","pursue","love"],
			["past","harm","heart","again"],
			["past","harm","love","again"],
			["past","see","present","danger"],
			["war","gain","distance","harmony"],
			["war","see","distance","harmony"],
		],
	],
	[
		"future",
		[
			["destination"],
			["equal","past"],
		],
	],
	[
		"gain",
		[
			["civilization","peace"],
			["future","escape"],
			["more","knowledge"],
			["portal","attack","weak"],
			["safety"],
			["truth","open","human","soul"],
		],
	],
	[
		"grow",
		[
			["collective","presence"],
			["shapers","presence"],
			["unbounded","create","new","future"],
		],
	],
	[
		"harm",
		[
			["danger","avoid"],
			["heart","forget","love"],
			["progress","pursue","more","war"],
		],
	],
	[
		"harmony",
		[
			["stability","future"],
			["together","end","mystery"],
		],
	],
	[
		"have",
		[
			["harmony","together"],
			["harmony","together","end","mystery"],
			["love","have","harmony"],
		],
	],
	[
		"heart",
		[
			["equal","mystery"],
			["heart"],
			["heart","heart"],
			["heart","heart","heart"],
			["heart","heart","heart","heart"],
			["lead","destiny"],
			["nourish","courage"],
			["path","complex","mystery","chaos"],
			["potential"],
		],
	],
	[
		"help",
		[
			["clear","barrier"],
			["enlightened","strong","victory"],
			["enlightenment","capture","all","portal"],
			["enlightenment","strong","victory"],
			["gain","create","pursue"],
			["gain","knowledge","inside","resistance"],
			["human","civilization","pursue","destiny"],
			["n","l","avoid","capture"],
			["resistance","capture","all","portal"],
			["resistance","strong","victory"],
			["shapers","create","future"],
			["them"],
			["truth"],
			["us"],
			["us","all"],
			["us","escape"],
			["us","progress","strong","victory"],
			["us","save","us"],
			["us","save","us","all"],
			["us","save","us","destroy"],
		],
	],
	[
		"hide",
		[
			["chaos","inside","body"],
			["impure","human","thought"],
			["journey","truth"],
			["path","future"],
			["resistance","advance","strong","together"],
			["them","inside","complex","intelligence"],
			["truth"],
		],
	],
	[
		"human",
		[
			["escape","all"],
			["evolution","create","more","field"],
			["evolution","unbounded"],
			["failure","unbounded"],
			["gain","safety"],
			["have","impure","civilization"],
			["heart","complex","potential"],
			["heart","strong","pure","key"],
			["intelligence","unbounded"],
			["knowledge","legacy"],
			["legacy","abandon","old","knowledge"],
			["legacy","have","abandon","now"],
			["love","strong","pure","key"],
			["love","unbounded"],
			["not","together","civilization","deteriorate"],
			["past","present","future"],
			["shapers","together","create","destiny"],
			["soul","strong","pure"],
			["soul","unbounded"],
			["unbounded","escape","all"],
			["weak"],
		],
	],
	[
		"ignore",
		[
			["human","chaos","lie"],
		],
	],
	[
		"imperfect",
		[
			["civilization","lose","key","data"],
			["love","create","chaos","soul"],
			["message","begin","human","chaos"],
			["truth","open","complex","answer"],
			["xm","message","human","chaos"],
		],
	],
	[
		"improve",
		[
			["advance","present"],
			["body","mind","soul"],
			["body","pursue","journey"],
			["future","together"],
			["human","shapers"],
			["mind","improve","courage","change"],
			["mind","journey","inside"],
		],
	],
	[
		"inside",
		[
			["mind","future"],
			["mind","inside","soul","harmony"],
			["mind","journey","perfection"],
			["xm","truth"],
		],
	],
	[
		"interrupt",
		[
			["enlightened","technology"],
			["enlightened","technology","capture","victory"],
			["evolution"],
			["message","gain","advance"],
			["message","lose","collective","potential"],
			["message","lose","shapers","potential"],
		],
	],
	[
		"journey",
		[
			["harmony"],
			["inside","discover","heart","truth"],
			["inside","improve","soul"],
			["inside","soul"],
			["link","portal"],
		],
	],
	[
		"key",
		[
			["link"],
			["potential","link"],
		],
	],
	[
		"knowledge",
		[
			["help","gain","victory"],
		],
	],
	[
		"lead",
		[
			["enlightenment","civilization"],
			["pursue","react","defend"],
			["resistance","question"],
		],
	],
	[
		"less",
		[
			["chaos","more","stability"],
			["harm","more","love"],
			["shield","more","harm"],
			["soul","more","mind"],
			["truth","more","chaos"],
		],
	],
	[
		"liberate",
		[
			["heart"],
			["human","future"],
			["portal"],
			["portal","liberate","human","mind"],
			["portal","potential"],
			["self","liberate","human","civilization"],
			["xm","portal","together"],
		],
	],
	[
		"lie",
		[
			["equal","future"],
		],
	],
	[
		"link",
		[
			["all","portal","create","field"],
			["field"],
			["key","field","success"],
			["us","heart","create","future"],
			["we","heart","create","future"],
		],
	],
	[
		"live",
		[
			["love","repeat"],
		],
	],
	[
		"liveagain",
		[
			["die","again","evolution"],
			["die","repeat","evolution"],
			["die","repeat","evolution","future"],
		],
	],
	[
		"lose",
		[
			["attack","retreat"],
			["danger","gain","safety"],
			["key","contemplate","future"],
			["love","destroy","human","soul"],
			["shapers","message","gain","chaos"],
		],
	],
	[
		"love",
		[
			["again"],
			["again","live","again"],
			["all"],
			["all","human"],
			["create","civilization"],
			["create","future"],
			["end","conflict"],
			["end","fear"],
			["equal","answer"],
			["equal","future"],
			["equal","key"],
			["equal","mystery"],
			["inside","resistance"],
			["mystery"],
			["nature","nourish","nature","together"],
			["nourish","courage"],
			["nourish","human"],
			["nourish","soul"],
			["now"],
			["potential"],
			["self"],
			["technology","advance","technology","now"],
			["together"],
			["your","self"],
		],
	],
	[
		"mind",
		[
			["body","live"],
			["body","soul","pure","human"],
			["equal","truth"],
			["open","live"],
			["technology","capture","human","soul"],
		],
	],
	[
		"more",
		[
			["courage","advance","human","heart"],
			["data","gain","portal","advance"],
			["heart"],
			["heart","more","courage"],
			["journey","less","destination"],
			["love"],
			["love","less","conflict","war"],
			["love","more","courage"],
		],
	],
	[
		"mystery",
		[
			["before","pure","knowledge","after"],
			["inside","heart"],
		],
	],
	[
		"n",
		[
			["l","have","portal","message"],
		],
	],
	[
		"nature",
		[
			["pure","defend"],
		],
	],
	[
		"nemesis",
		[
			["lose","portal","love","chaos"],
		],
	],
	[
		"nourish",
		[
			["heart","nourish","soul"],
			["journey"],
			["love"],
			["mind","journey"],
			["portal","avoid","weak","field"],
			["xm","create","thought"],
			["xm","portal"],
		],
	],
	[
		"now",
		[
			["you","all","star"],
		],
	],
	[
		"nzeer",
		[
			["hide","us","equal","them"],
			["legacy","create","future"],
			["shapers","struggle","knowledge"],
			["technology","mind","evolution"],
			["technology","perfection"],
			["technology","perfection","truth"],
		],
	],
	[
		"old",
		[
			["nature","less","strong","now"],
		],
	],
	[
		"open",
		[
			["human","weak"],
			["mind","open","soul","love"],
			["n","l","search","inside"],
		],
	],
	[
		"openall",
		[
			["link","create","star"],
			["portal"],
			["portal","success"],
			["simple","truth"],
		],
	],
	[
		"past",
		[
			["again","present","again"],
			["barrier","create","future","journey"],
			["chaos","create","future","harmony"],
			["equal","future"],
			["path","create","future","journey"],
			["peace","difficult"],
			["present","future"],
			["present","future","n","l"],
		],
	],
	[
		"path",
		[
			["balance"],
			["peace"],
			["peace","difficult"],
			["restraint","strong","safety"],
		],
	],
	[
		"peace",
		[
			["path","nourish","present"],
			["simple","journey"],
			["stability","future"],
			["worth","more"],
		],
	],
	[
		"perfection",
		[
			["balance","safety","all"],
			["past","peace"],
			["path","peace"],
		],
	],
	[
		"portal",
		[
			["attack","danger","pursue","safety"],
			["barrier","defend","human","shapers"],
			["change","civilization","end"],
			["create","danger","pursue","safety"],
			["die","civilization","die"],
			["have","truth","data"],
			["improve","human","future","civilization"],
			["potential","change","future"],
			["potential","help","human","future"],
			["presence"],
		],
	],
	[
		"potential",
		[
			["new","n","l","destination"],
			["truth","harmony"],
			["xm","peace"],
			["xm","war"],
		],
	],
	[
		"presence",
		[
			["lie","equal","future","consequence"],
		],
	],
	[
		"present",
		[
			["chaos","create","future","civilization"],
			["struggle","worth","strong","victory"],
		],
	],
	[
		"pure",
		[
			["body"],
			["chaos"],
			["human"],
			["human","failure","now","chaos"],
			["love","escape","death"],
			["potential"],
			["truth"],
		],
	],
	[
		"pursue",
		[
			["1","3","3","1"],
			["complex","truth"],
			["conflict"],
			["conflict","war","advance","chaos"],
			["destiny"],
			["human","potential","evolution","unbounded"],
			["human","potential","evolution"],
			["more","mystery"],
			["nature"],
			["path","outside","shapers","lie"],
			["pure","body"],
			["truth"],
			["xm"],
		],
	],
	[
		"question",
		[
			["all"],
			["attack"],
			["conflict","data"],
			["heart","discover","truth","self"],
			["hide","truth"],
			["human","truth"],
			["less","forget","all","lie"],
			["potential","mystery"],
			["potential","mystery","journey"],
			["potential","mystery","journey","grow"],
			["shapers"],
			["shapers","chaos"],
			["truth"],
			["truth","gain","future"],
		],
	],
	[
		"react",
		[
			["impure","civilization"],
			["pure","truth"],
			["rebel","question","shapers","lie"],
		],
	],
	[
		"rebel",
		[
			["thought","evolution","destiny","now"],
		],
	],
	[
		"repair",
		[
			["1","3","3","1"],
			["all","liveagain"],
			["heart"],
			["inside","repair","human","soul"],
			["nature","balance"],
			["portal","shield"],
			["present","repair","human","soul"],
			["soul","less","human","harm"],
		],
	],
	[
		"resistance",
		[
			["gain","all","victory","osiris"],
		],
	],
	[
		"restraint",
		[
			["fear","avoid","danger"],
			["path","gain","harmony"],
		],
	],
	[
		"retreat",
		[
			["search","safety"],
		],
	],
	[
		"safety",
		[
			["together"],
		],
	],
	[
		"save",
		[
			["human","civilization","destroy","portal"],
		],
	],
	[
		"search",
		[
			["data","discover","path"],
			["destiny","create","pure","future"],
			["heart"],
			["potential"],
			["soul","inside","heart"],
			["soul","inside","love"],
			["truth","save","civilization"],
			["xm","distance","destination"],
			["xm","portal"],
			["xm","save","portal"],
			["your","heart"],
			["your","heart","discover","courage"],
		],
	],
	[
		"see",
		[
			["heart","see","human","truth"],
			["n","l"],
			["n","l","pure","perfection"],
			["n","l","together","again"],
			["shapers"],
			["truth","now"],
			["truth","see","future"],
			["truth","see","future","begin"],
			["unbounded"],
		],
	],
	[
		"separate",
		[
			["attack"],
			["future","evolution"],
			["future","pursue"],
			["mind","body","discover","enlightenment"],
			["truth","lie","shapers","future"],
			["weak","ignore","truth"],
		],
	],
	[
		"shapers",
		[
			["chaos","pure","harm"],
			["create","chaos","change","heart"],
			["have","strong","path"],
			["lead","human","complex","journey"],
			["message","end","civilization"],
			["mind","complex","harmony"],
			["past","present","future"],
			["portal","data","create","chaos"],
			["portal","message","destroy","civilization"],
			["portal","mind","restraint"],
			["see","complex","path","destiny"],
			["see","potential","evolution"],
			["want","human","mind","future"],
		],
	],
	[
		"share",
		[
			["enlightenment","knowledge"],
			["key","save","all"],
			["resistance","message"],
		],
	],
	[
		"shield",
		[
			["defend","human","civilization"],
			["mind"],
			["mind","clearall","chaos","xm"],
			["portal"],
		],
	],
	[
		"simple",
		[
			["civilization","impure","weak"],
			["heart","simple","answer"],
			["message","complex","idea"],
			["old","truth","journey","inside"],
			["truth","all","human","star"],
			["truth","breathe","nature"],
			["truth","forget","easy","success"],
			["truth","shapers","destroy","civilization"],
		],
	],
	[
		"soul",
		[
			["rebel","human","die"],
		],
	],
	[
		"star",
		[
			["courage","difficult"],
			["nature"],
		],
	],
	[
		"stay",
		[
			["strong","together","defend","resistance"],
			["together","defend","truth"],
			["truth","escape","impure","love"],
		],
	],
	[
		"strong",
		[
			["heart"],
			["idea","pursue","truth"],
			["inside","love"],
			["love","equal","strong","shield"],
			["mind"],
			["portal","strong","field"],
			["resistance","capture","portal"],
			["soul"],
			["together","avoid","war"],
			["together","war","together","chaos"],
			["together","war","together","destiny"],
		],
	],
	[
		"struggle",
		[
			["defend","shapers","danger"],
			["improve","human","soul"],
		],
	],
	[
		"technology",
		[
			["capture","victory"],
			["intelligence","grow","unbounded"],
			["intelligence","see","all"],
			["intelligence","see","all","unbounded"],
		],
	],
	[
		"together",
		[
			["discover","harmony","equal"],
			["end","mystery"],
			["progress","recharge","present","journey"],
			["pure","journey"],
			["pursue","safety"],
			["strong"],
		],
	],
	[
		"truth",
		[
			["idea","discover","xm"],
			["nourish","soul"],
		],
	],
	[
		"unbounded",
		[
			["mind"],
		],
	],
	[
		"use",
		[
			["courage","discover","love"],
			["key"],
			["key","together","create","star"],
			["mind","use","courage","change"],
			["restraint","follow","easy","path"],
		],
	],
	[
		"want",
		[
			["1","3","3","1"],
			["new","destination","ignore","consequence"],
			["truth","now"],
			["truth","pursue","difficult","path"],
		],
	],
	[
		"war",
		[
			["create","danger"],
			["destroy","future"],
			["not","worth","consequence"],
		],
	],
	[
		"weak",
		[
			["body","strong","heart"],
			["human","destiny","destroy","civilization"],
			["portal","weak","field"],
		],
	],
	[
		"xm",
		[
			["create","complex","human","destiny"],
			["die","chaos","live"],
			["grow","creativity"],
			["have","mind","journey"],
			["key","knowledge"],
			["nourish","civilization"],
			["nourish","strong","idea"],
			["path","future","destiny","harmony"],
			["portal","share","your","creativity"],
			["share","your","creativity"],
		],
	],
	[
		"you",
		[
			["adapt"],
			["hide","chaos"],
			["hide","chaos","inside","body"],
			["see","n","l","again"],
		],
	],
	[
		"your",
		[
			["message","clear","use","chaos"],
		],
	],
]);
//end-auto-generated
function getNextGlyphOptions(currentSequence, autocomplete = false) {
	let sequenceArray = currentSequence.split(',');
	if (sequenceArray.length === 0) {
		return {
			sequence: null,
			options: [],
		};
	}

	const initialGlyph = sequenceArray[0];
	if (!glyphSequencesMap.has(initialGlyph)) {
		return {
			sequence: null,
			options: [],
		};
	}

	const sequences = glyphSequencesMap.get(initialGlyph);

	// Validate sequenceArray as a valid (partial or full) sequence
	let validSequenceArray = [initialGlyph];
	outerLoop: for (let i = 1; i < sequenceArray.length; i++) {
		for (let seq of sequences) {
			if (seq.slice(0, i).join(',') === sequenceArray.slice(1, i + 1).join(',')) {
				validSequenceArray.push(sequenceArray[i]);
				continue outerLoop;
			}
		}
		// If the glyph is not valid, break and use the last valid sequence
		break;
	}
	sequenceArray = validSequenceArray;

	const subsequenceMap = new Map();
	sequences.forEach((sequence) => {
		for (let i = 0; i < sequence.length; i++) {
			const subsequence = [initialGlyph, ...sequence.slice(0, i)].join(',');
			if (!subsequenceMap.has(subsequence)) {
				subsequenceMap.set(subsequence, new Set());
			}
			subsequenceMap.get(subsequence).add(sequence[i]);
		}
	});

	if (!autocomplete) {
		return {
			sequence: sequenceArray.join(','),
			options: Array.from(subsequenceMap.get(sequenceArray.join(',')) ?? []),
		};
	} else {
		let currentSubsequence = sequenceArray.join(',');
		let nextOptions = subsequenceMap.get(currentSubsequence) ? Array.from(subsequenceMap.get(currentSubsequence)) : [];

		while (subsequenceMap.has(currentSubsequence) && subsequenceMap.get(currentSubsequence).size === 1) {
			const nextGlyph = Array.from(subsequenceMap.get(currentSubsequence))[0];
			sequenceArray.push(nextGlyph);
			currentSubsequence = sequenceArray.join(',');

			nextOptions = subsequenceMap.get(currentSubsequence) ? Array.from(subsequenceMap.get(currentSubsequence)) : [];
			const fullSequence = [...sequenceArray.slice(1)].join(',');
			const isFullSequence = sequences.some((seq) => seq.join(',') === fullSequence);

			if (nextOptions.length > 1 || isFullSequence) {
				break;
			}
		}
		return {
			sequence: currentSubsequence,
			options: nextOptions,
		};
	}
}
function getRandomSequence() {
	const entriesArray = [...glyphSequencesMap.entries()];
	const [key, sequences] = entriesArray[Math.floor(Math.random() * entriesArray.length)];
	const randomSequence = sequences[Math.floor(Math.random() * sequences.length)];
	return [key, ...randomSequence].join(',');
}
export { glyphSequencesMap, getNextGlyphOptions, getRandomSequence };
